_target_: src.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  channels: 3
  width: 32
  height: 32
  num_classes: 10
  hidden_size: 64
  learning_rate: 2e-4
